{"tid":1902308,"cid":15,"subCid":0,"title":"bitfinex 2/28 17:00 被DDOS","createTime":"2020-02-28T09:23:35.000Z","updateTime":"2020-02-28T09:36:13.000Z","uid":90595,"like":0,"dislike":0,"uniUserReply":1,"replies":[{"pid":"3f071d35583f4700df1c3eb34e119568a19e87b5","tid":1902308,"uid":90595,"like":0,"dislike":0,"score":0,"citedBy":0,"replyTime":"2020-02-28T09:23:35.000Z","msg":"website已down<br />\n<br />\n<a href=\"https://twitter.com/bitfinex/status/1233321316641640448\" data-sr-url=\"https://r.lihkg.com/link?u=https%3A%2F%2Ftwitter.com%2Fbitfinex%2Fstatus%2F1233321316641640448&d=2%2B%2BG2pXT7lWIneVuf1o%2BJA%2BoCD4UrwaevtQIqI6x5z0%3D&h=e0e97381\" data-ef-url=\"https://embed.lih.kg/frame?u=https%3A%2F%2Ftwitter.com%2Fbitfinex%2Fstatus%2F1233321316641640448&h=eddcb819\" data-auto-link target=\"_blank\">https://twitter.com/bitfinex/status/1233321316641640448</a><br />\n<br />\nWe are investigating what seems like a distributed denial-of-service (DDoS) attack. We will keep everyone updated on here and our status page <a href=\"https://t.co/u3pYCVVGQq\" data-sr-url=\"https://r.lihkg.com/link?u=https%3A%2F%2Ft.co%2Fu3pYCVVGQq&d=2%2B%2BG2pXT7lWIneVuf1o%2BJA%2BoCD4UrwaevtQIqI6x5z0%3D&h=725465f1\" data-auto-link target=\"_blank\">https://t.co/u3pYCVVGQq</a> as we know more."},{"pid":"e405f7ee18a2092c35ebcc1c211d42282e807b54","tid":1902308,"uid":90595,"like":0,"dislike":0,"score":0,"citedBy":0,"replyTime":"2020-02-28T09:26:18.000Z","msg":"<img src=\"https://i.imgur.com/NLfo8ii.jpg\" data-thumbnail-src=\"https://i.lih.kg/thumbnail?u=https%3A%2F%2Fi.imgur.com%2FNLfo8ii.jpg&h=7711801c&s={SIZE}\" />"},{"pid":"4c1c8ec598f878ad1746b4580a14daf4f17862ea","tid":1902308,"uid":90595,"like":0,"dislike":0,"score":0,"citedBy":0,"replyTime":"2020-02-28T09:29:10.000Z","msg":"有病<br />\npanic sell緊時有ddos<br />\n最後一下websocket success係1702<br />\n<img src=\"https://i.imgur.com/J73pgkT.jpg\" data-thumbnail-src=\"https://i.lih.kg/thumbnail?u=https%3A%2F%2Fi.imgur.com%2FJ73pgkT.jpg&h=d27762de&s={SIZE}\" />"},{"pid":"4217bb9483fe351b28ef66e0d16eb546be521270","tid":1902308,"uid":90595,"like":0,"dislike":0,"score":0,"citedBy":0,"replyTime":"2020-02-28T09:36:13.000Z","msg":"websocket不停timeout<br />\n<code>\nException in thread Thread-2:\nTraceback (most recent call last):\n  File &quot;C:\\Python\\Python37\\lib\\threading.py&quot;, line 917, in _bootstrap_inner\n    self.run()\n  File &quot;C:\\Python\\Python37\\lib\\threading.py&quot;, line 865, in run\n    self._target(*self._args, **self._kwargs)\n  File &quot;C:\\Users\\Win10\\Desktop\\bitfinex\\bitfinex-api-py\\bfxapi\\websockets\\generic_websocket.py&quot;, line 111, in start_loop\n    loop.run_until_complete(self._run_socket())\n  File &quot;C:\\Python\\Python37\\lib\\asyncio\\base_events.py&quot;, line 573, in run_until_complete\n    return future.result()\n  File &quot;C:\\Users\\Win10\\Desktop\\bitfinex\\bitfinex-api-py\\bfxapi\\websockets\\generic_websocket.py&quot;, line 144, in _run_socket\n    async with websockets.connect(self.host) as websocket:\n  File &quot;C:\\Python\\Python37\\lib\\site-packages\\websockets\\client.py&quot;, line 517, in __aenter__\n    return await self\n  File &quot;C:\\Python\\Python37\\lib\\site-packages\\websockets\\client.py&quot;, line 547, in __await_impl__\n    extra_headers=protocol.extra_headers,\n  File &quot;C:\\Python\\Python37\\lib\\site-packages\\websockets\\client.py&quot;, line 296, in handshake\n    raise InvalidStatusCode(status_code)\nwebsockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 408\n</code>"}]}